version: '3.1'

services:
  postgres:
    image: postgres:15.2-alpine
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 00000000
      # PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    restart: unless-stopped
    # volumes:
      # - ./backend/extra/init.sql:/docker-entrypoint-initdb.d/init.sql
      # - ./backend/app/data/pg/:/var/lib/postgresql/data/
    networks:
      - backend

networks:
  backend:
    name: backend